CREATE TABLE IF NOT EXISTS branches (
    id CHAR(26) PRIMARY KEY,
    company_id CHAR(26) NOT NULL,
    name VARCHAR(255) NOT NULL,
    address VARCHAR(255),
    timezone VARCHAR(255) NOT NULL DEFAULT 'Asia/Makassar',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP WITH TIME ZONE,

    FOREIGN KEY (company_id) REFERENCES companies(id)
);